---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: us-east-1
  version: "1.22"
managedNodeGroups:
- name: ${CLUSTER_NAME}-nodegroup
  labels:
    role: test
  instanceType: t2.small
  desiredCapacity: 2
  minSize: 2
  maxSize: 4